### ISSUE TITLE
Retina Sizing Not Working Correctly

### ISSUE THREAD

**Issue by benjaminx3000** [sprity/sprity#11]
When processing sprites with an  @2x variant, css dimensions should be half of what the full size image should be.
For example, using the options 
```
dimension: [
	{ratio: 1, dpi: 72},
	{ratio: 2, dpi: 144}
],
```
and a source image is 50px by 50px,
the css output should be 
```
{height: 25px, width: 25px}
@media(-webkit-min-device-pixel-ratio: 2) {
    background-image: url('sprite@2x.png);
    background-size: 25px 25px;
}
```

The sprite image files being out put seem to be correct, just the css template seems to be be applied backwards.

**Comment by lbineau** [comment]
+1 Same for me ! The .scss has the same problem.

**Comment by existemi** [comment]
+1. Also experiencing this.

**Comment by dreamyguy** [comment]
+1 We were staring at the parameters, loosing hair and asking ourselves: is this right???

**Comment by benjaminx3000** [comment]
I've got a temporary workaround using a template, however it's hardcoded to handle a  1 and 2 ration dimension. It's currently written to produce a less file.

```
{{#each layouts}}
.{{cssesc classname}} {
	{{#each sprites}}
		{{#if dpi}}
		@media (min-device-pixel-ratio: {{ratio}}), (min-resolution: {{dpi}}dppx) {
			.{{cssesc ../../classname}} {
				background-image: url('{{escimage url}}');
				background-size: ({{width}}px / {{ratio}}) ({{height}}px / {{ratio}});
			}
		}
		{{else}}
		background-image: url('{{escimage url}}');
		display: inline-block;
		{{/if}}
	{{/each}}

	{{#each layout.items}}
	&.{{meta.name}} {
		background-position: -({{x}}px / 2) -({{y}}px / 2);
		width: ({{width}}px / 2);
		height: ({{height}}px / 2);
	}
	{{/each}}
}
{{/each}}
```
