### ISSUE TITLE
Some modules have a mistake.

### ISSUE THREAD

**Issue by rayliao** [sprity/sprity#17]
![qq 20150615205716](https://cloud.githubusercontent.com/assets/5601068/8160341/677e0e02-13a1-11e5-8e00-59fe04139874.jpg)
![qq 20150615205729](https://cloud.githubusercontent.com/assets/5601068/8160344/6ddbd54a-13a1-11e5-8c66-8c18d381a4a3.jpg)

**Comment by rayliao** [comment]
![qq 20150615210137](https://cloud.githubusercontent.com/assets/5601068/8160395/ee2f169e-13a1-11e5-91b6-b0eaf093b308.jpg)
Always installation is not successful.

**Comment by aslansky** [comment]
This seems to be a problem with the [lwip](https://github.com/EyalAr/lwip) installation on window. You can either use another image processor like [sprity-gm](https://github.com/sprity/sprity-gm) or open a issue at the lwip github page.
