### ISSUE TITLE
The "dimension" option only seems to work on the images

### ISSUE THREAD

**Issue by ZeeCoder** [sprity/sprity#19]
Image generation respects this option, generating "@2", "@3" etc images based on the configuration.
But the resulting style - be it css or scss - always references a normal, and a @2-retina background image, even if I leave out the dimension parameter altogether.

**Comment by ZeeCoder** [comment]
@aslansky ?

**Comment by aslansky** [comment]
If I use the command line with `sprity ... --style style.css -d 2:192 -d 1:72 -d 3:384` i get:

```
.icon {
  background-image: url("dist/icons.png");
}
@media (-webkit-min-device-pixel-ratio: 2),
(min-resolution: 192dpi) {
  .icon {
    background-image: url("dist/icons@2x.png");
    background-size: 149px 133px;
  }
}
@media (-webkit-min-device-pixel-ratio: 3),
(min-resolution: 384dpi) {
  .icon {
    background-image: url("dist/icons@3x.png");
    background-size: 149px 133px;
  }
}
```

So I am not sure how to reproduce what you are describing. Can you give me some more hints?

**Comment by ZeeCoder** [comment]
You can take a look at: https://github.com/sprity/sprity-sass/issues/3#issuecomment-134567710.

Basically after I played around with the cli, I could make the gulp task work.

If I encounter the error again, I'll report back. :)
