### ISSUE TITLE
Format JPG is not working

### ISSUE THREAD

**Issue by vsorrokin** [sprity/sprity#3]
I use sprity with gulp and everything works fine. But I can't make work the "format" option. JPG/jpg value is not working at all - sprity continues to generate large size png file! Also can I set level of jpg compression?

**Comment by aslansky** [comment]
JPG should be fixed in version 1.0.4. At the moment you can not set the compression level.

**Comment by aslansky** [comment]
I close this ticket and open a new one for the compression option.

**Comment by aslansky** [comment]
See #12
