### ISSUE TITLE
How to switch image engines with the engine option in gulp?

### ISSUE THREAD

**Issue by rayliao** [sprity/sprity#37]
If I want to switch to sprity-gm, like this ?

```
sprity.src({
        src:  'images/*.png',
        style: '_' + sprityConfig.name + '.scss',
        format: 'png',
        engine: 'gm',
        orientation: 'left-right',
        template: './sprity-css.hbs',
        processor: 'scss'
    })
```

**Comment by stephanedemotte** [comment]
this is how i use imagemagick:

```
     engine: 'gm',
     format: 'png',
     'gm-use-imagemagick': true,
```

don't forget to install it ;)

```
brew install imagemagick
```

**Comment by rayliao** [comment]
It doesn't work, I have installed imagemagick.
![qq 20151104223718](https://cloud.githubusercontent.com/assets/5601068/10941154/15cefc24-8345-11e5-9baa-1d3023109d6b.jpg)

**Comment by rayliao** [comment]
When I use sprity-gm, Imagemagick and GraphicsMagick must to install?

**Comment by stephanedemotte** [comment]
nope you have to install it before 
```
brew install imagemagick
```

**Comment by rayliao** [comment]
My system is win10, It need to restart after I install Imagemagick and GraphicsMagick.

**Comment by stephanedemotte** [comment]
Check this for install on windows

https://www.npmjs.com/package/gulp-image-resize
