### ISSUE TITLE
Set interpolation to lwip by options in sprity

### ISSUE THREAD

**Issue by cztoky** [sprity/sprity#5]
Hi guys,

I dont know how to set "lwip-interpolation" to "grid" by sprity options. There is just engine. Can you help me? 

I have problem with lwip simillar to https://github.com/aslansky/css-sprite/issues/42

Thank you for any answer. 
cztoky

**Comment by aslansky** [comment]
```
sprity.create({
  'lwip-interpolation': 'cubic'
}, cb);
```

on command line you can use --lwip-interpolation cubic

You find documentation for that feature here: https://github.com/sprity/sprity-lwip#options

The problems you having are problems with the lwip image processor. I would say try if it helps setting a different interpolation. If not you should consider switching to [sprity-canvas](https://github.com/sprity/sprity-canvas) or [sprity-gm](https://github.com/sprity/sprity-gm). Unfortunately both engines depend on external tools so more installation effort may be required.

**Comment by cztoky** [comment]
Thank you for answer!

I understand .. And question is how to use by gulp:

```
gulp.task('pngSprite', function () {
  return sprity.src({
    src: settings.pngSprite.entry,
    processor: 'sass',
    style: 'pngSprite.scss',
    template: './png.hbs',
    dimension: [{ ratio: 1, dpi: 192 }, { ratio: 2, dpi: 192 }]
  })
  .pipe( gulpif('*.png', gulp.dest(settings.pngSprite.dest), gulp.dest(settings.pngSprite.sass)) )
});
```

**Comment by aslansky** [comment]
```
gulp.task('pngSprite', function () {
  return sprity.src({
    src: settings.pngSprite.entry,
    processor: 'sass',
    style: 'pngSprite.scss',
    template: './png.hbs',
   'lwip-interpolation': 'cubic'
    dimension: [{ ratio: 1, dpi: 192 }, { ratio: 2, dpi: 192 }]
  })
  .pipe( gulpif('*.png', gulp.dest(settings.pngSprite.dest), gulp.dest(settings.pngSprite.sass)) )
});
```

should work.
